# Generated by Django 5.2.1 on 2025-06-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_alter_tasklist_options_tasklist_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
